name: My Workflow

on:
  push
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        run: |
          value=$(uname -s)
          echo "os_name=$value" >> "$GITHUB_ENV"
      - name: Use the value
        run: |
          echo "${{ env.os_name }}" # This will output 'yellow'
