name: My Workflow

on:
  push
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        run: |
          echo "action_state=maimi" >> "$GITHUB_ENV"
      - name: Use the value
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
