name: My Workflow

on:
  push
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        run: echo "Hello, world!"
        id: my-step
      - name: Use Variable
        run: echo "The previous step said ${{ env.MY_VAR }}"
        env:
          MY_VAR: ${{ steps.my-step.outputs.stdout }}
