name: Deploy to Azure

on:
  workflow_dispatch:

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID_SUNILNGVLI }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID_SUNILNGVLI }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID_SUNILNGVLI }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET_SUNILNGVLI }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_SUNILNGVLI_SDK }}
    
    - run: |
        az account show

    - name: Azure account details check
      run: az account show

    - name: Terraform init
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.4.0"

    - name: Checkout terraform repo
      uses: actions/checkout@v2
      with:
        repository: sunil-tf-modules/ahsaccv3-infra-demo
        ref: main
        path: ahsaccv3-infra-demo
    
    - name: Check the files in the repo
      working-directory: ./ahsaccv3-infra-demo/core
      run: |
        ls -l
    
    - name: Terraform init
      working-directory: ./ahsaccv3-infra-demo/core
      run: terraform init
      
    - name: Terraform validate
      working-directory: ./ahsaccv3-infra-demo/core
      run: terraform validate

    - name: Terraform plan
      working-directory: ./ahsaccv3-infra-demo/core
      run: terraform plan -var-file=dev.tfvars -out=dev.tfplan

#     - name: Terraform apply
#       working-directory: ./ahsaccv3-infra-demo/core
#       run: terraform apply -auto-approve
