name: if-else condition with inputs

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Enter a value"
        default: "hi"
        type: string

jobs:
  condition:
    runs-on: ubuntu-latest
    steps:
      - name: if condition with user input
        shell: bash
        run: |
          # Hi
          if [ ${{ inputs.action }} == "hi" ]; then
            echo "default option - 'Hi'"
          # Hello
          elif [ ${{ inputs.action }} == "hello" ]; then
            echo "user entered 'Hello'"
          # Hola
          elif [ ${{ inputs.action }} == "hola" ]; then
            echo "user entered 'Hola'"
          # Bonjour
          elif [ ${{ inputs.action }} == "bonjour" ]; then
            echo "user entered 'Bonjour'"          
          else
            echo "no value entered"
          fi
