name: Read Vaules From JSON

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"json_include\":[{\"json_project\":\"json_foo\",\"json_config\":\"json_Debug\"},{\"json_project\":\"json_bar\",\"json_config\":\"json_Release\"}]}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: env
