# File: .github/workflows/az-login.yml
name: Terraform IAC

on: 
  [push]
  
jobs:
  build:
    strategy:
      matrix:
        user_input:
          - "proceed"
          - "abort"
    runs-on: ubuntu-latest
    steps:
      - name: Step 01 - Validate user input
        if: matrix.user_input == 'abort'
        run: exit 1
      - name: Step 02 - Proceed to next step
        if: matrix.user_input == 'proceed'
        run: echo "Proceeding to next step"  