# File: .github/workflows/az-login.yml
name: Terraform IAC

on: 
  [push]

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Get user input
        run: |
          echo "Please enter 'proceed' or 'abort':"
          read user_input
          echo "User input: $user_input"
      - name: Validate user input
        if: ${{ env.user_input == 'abort' }}
        run: exit 1
      - name: Proceed to next step
        if: ${{ env.user_input == 'proceed' }}
        run: echo "Proceeding to next step"
  